### ISSUE TITLE
Guid when GuidRepresentation is Unspecified

### ISSUE THREAD

**Issue by franklupo** [chrisdrobison/AspNetCore.MongoDb#8]
MongoDB.Bson.BsonSerializationException: An error occurred while serializing the Id property of class AspNetCore.Authentication.Cookies.MongoDb.Ticket: GuidSerializer cannot serialize a Guid when GuidRepresentation is Unspecified.

**Comment by chrisdrobison** [comment]
I'm assuming this has to do with some recent changes in the v3 driver which removed legacy Guid format support. Try following the instructions here: https://www.mongodb.com/docs/drivers/csharp/current/fundamentals/serialization/guid-serialization/ to setup the serializer with guid representation and see if that fixes the problem. I should probably move this library away from using GUID as the ID

**Comment by franklupo** [comment]
works perfectly.

thanks
